export const environment = {
  production: true,
  phegyDomain: "phegy.tech",
  phegyApiDomain: "api.phegy.tech",
  phegyApiUrl: "https://api.phegy.tech",
  phegyCdnUrl: "https://cdn.phegy.tech",
  authPrefix: "Bearer ",
  authHeader: "Authorization",
  authTokenKey: "phegyAuthToken",
  refreshPrefix: "Bearer ",
  refreshHeader: "Authorization-Refresh",
  refreshTokenKey: "phegyAuthRefreshToken",
  preferredThemeKey: "phegyPreferredTheme",
  defaultPageSize: 8,
  minUsernameLength: 3,
  maxUsernameLength: 36,
  minEmailLength: 3,
  maxEmailLength: 254,
  minPasswordLength: 6,
  maxPasswordLength: 50,
  newRequestDateKey: "phegyNewRequestDateKey",
};
